use TOKOBANGUNAN

CREATE TABLE RETUR(
NO_RETUR CHAR (10) PRIMARY KEY,
KD_MEMBER CHAR (10) FOREIGN KEY REFERENCES MEMBER (KD_MEMBER),
TGL_RETUR DATETIME NOT NULL,
KETERANGAN VARCHAR (100) NOT NULL
);


CREATE TABLE CUSTOMERSERVICE (
KD_PEGAWAI CHAR (10) PRIMARY KEY,
KD_MEMBER CHAR (10) FOREIGN KEY REFERENCES MEMBER (KD_MEMBER),
NAMA_MEMBER VARCHAR (30) NOT NULL,
USERNAME VARCHAR (50) NOT NULL, 
PASS VARCHAR (20) NOT NULL
);


CREATE TABLE MERCHANDISE (
KD_HADIAH CHAR (10) PRIMARY KEY,
KATEGORI VARCHAR (10) NOT NULL,
KD_MEMBER CHAR (10) FOREIGN KEY REFERENCES MEMBER (KD_MEMBER),
JENIS VARCHAR (10) NOT NULL
);


CREATE TABLE MEMBER (
KD_MEMBER CHAR (10) PRIMARY KEY,
NAMA_MEMBER VARCHAR (50) NOT NULL,
ALAMAT VARCHAR (100) NOT NULL,
NO_TELP VARCHAR (12) NOT NULL, 
NO_KTP VARCHAR (16) NOT NULL,
EMAIL VARCHAR (30) NOT NULL,
POIN VARCHAR (10) NOT NULL
);


CREATE TABLE PENJUALAN (
KD_NOTA CHAR (10) PRIMARY KEY,
KD_KASIR CHAR (10) FOREIGN KEY REFERENCES KASIR (KD_KASIR),
TANGGAL DATETIME NOT NULL,
KD_MEMBER CHAR (10) FOREIGN KEY REFERENCES MEMBER (KD_MEMBER),
TOTAL VARCHAR (10) NOT NULL
);


CREATE TABLE KASIR(
KD_KASIR CHAR (10) PRIMARY KEY,
NAMA VARCHAR (50) NOT NULL,
USER_KASIR VARCHAR(50) NOT NULL,
PASS_KASIR VARCHAR (20) NOT NULL
);

CREATE TABLE DETAIL_PENJUALAN(
ID_DETAILPENJ CHAR (10) PRIMARY KEY,
HARGA NUMERIC (18,0) NOT NULL,
JUMLAH INT NOT NULL,
KD_BARANG CHAR (10) FOREIGN KEY REFERENCES BARANG (KD_BARANG),
NO_PAJAK CHAR (10) FOREIGN KEY REFERENCES PAJAK (NO_PAJAK),
KD_NOTA CHAR (10) FOREIGN KEY REFERENCES PENJUALAN (KD_NOTA)
);


CREATE TABLE KREDIT(
NO_KREDIT CHAR (10) PRIMARY KEY,
TANGGAL_KREDIT DATETIME,
ID_DETAILPENJ CHAR (10) FOREIGN KEY REFERENCES DETAIL_PENJUALAN (ID_DETAILPENJ),
JUMLAH_BARANG INT NOT NULL,
TGL_LUNAS DATETIME,
LAMA_KREDIT VARCHAR (10) NOT NULL,
NILAI_KREDIT VARCHAR (10) NOT NULL
);


CREATE TABLE PAJAK(
NO_PAJAK CHAR (10) PRIMARY KEY,
JUMLAH_PAJAK INT NOT NULL,
TGL_BAYAR DATETIME
);


CREATE TABLE BARANG(
KD_BARANG CHAR (10) PRIMARY KEY,
NAMA_BARANG VARCHAR (30) NOT NULL,
HARGA_BARANG NUMERIC (18,0) NOT NULL,
JUMLAH_BARANG INT NOT NULL,
STOK VARCHAR (10)
);


CREATE TABLE PEMBELIAN(
KD_BELI CHAR (10) PRIMARY KEY,
TGL_BELI DATETIME,
JUMLAH_BARANG INT NOT NULL,
SUBTOTAL VARCHAR (10) NOT NULL
);

CREATE TABLE DETAIL_PEMBELIAN(
KD_BELI CHAR (10) FOREIGN KEY REFERENCES PEMBELIAN (KD_BELI),
KD_BARANG CHAR (10) FOREIGN KEY REFERENCES BARANG (KD_BARANG),
TGL_BELI DATETIME,
TOTAL VARCHAR (10) NOT NULL
);

CREATE TABLE SUPPLIER(
KD_SUPPLIER CHAR (10) PRIMARY KEY,
KD_BELI CHAR (10) FOREIGN KEY REFERENCES PEMBELIAN (KD_BELI),
NAMA VARCHAR(50) NOT NULL,
ALAMAT VARCHAR (100) NOT NULL,
NO_TELP VARCHAR (12) NOT NULL, 
EMAIL VARCHAR (20) NOT NULL
);

SELECT * FROM RETUR
SELECT * FROM CUSTOMERSERVICE
SELECT * FROM MERCHANDISE
SELECT * FROM MEMBER
SELECT * FROM PENJUALAN
SELECT * FROM KASIR
SELECT * FROM DETAIL_PENJUALAN
SELECT * FROM KREDIT
SELECT * FROM PAJAK
SELECT * FROM BARANG
SELECT * FROM PEMBELIAN
SELECT * FROM DETAIL_PEMBELIAN
SELECT * FROM SUPPLIER