create database TOKOBANGUNAN07
use TOKOBANGUNAN07

CREATE TABLE RETUR(
NO_RETUR CHAR (10) PRIMARY KEY,
KD_MEMBER CHAR (10) FOREIGN KEY REFERENCES MEMBER (KD_MEMBER),
TGL_RETUR DATETIME NOT NULL,
KETERANGAN VARCHAR (100) NOT NULL
);


CREATE TABLE CUSTOMERSERVICE (
KD_PEGAWAI CHAR (10) PRIMARY KEY,
KD_MEMBER CHAR (10) FOREIGN KEY REFERENCES MEMBER (KD_MEMBER),
NAMA_MEMBER VARCHAR (30) NOT NULL,
USERNAME VARCHAR (50) NOT NULL, 
PASS VARCHAR (20) NOT NULL
);


CREATE TABLE MERCHANDISE (
KD_HADIAH CHAR (10) PRIMARY KEY,
KATEGORI VARCHAR (10) NOT NULL,
KD_MEMBER CHAR (10) FOREIGN KEY REFERENCES MEMBER (KD_MEMBER),
JENIS VARCHAR (10) NOT NULL
);


CREATE TABLE MEMBER (
KD_MEMBER CHAR (10) PRIMARY KEY,
NAMA_MEMBER VARCHAR (50) NOT NULL,
ALAMAT VARCHAR (100) NOT NULL,
NO_TELP VARCHAR (12) NOT NULL, 
NO_KTP VARCHAR (16) NOT NULL,
EMAIL VARCHAR (30) NOT NULL,
POIN VARCHAR (10) NOT NULL
);


CREATE TABLE PENJUALAN (
NO_NOTA CHAR (5) PRIMARY KEY,
KD_KASIR CHAR (10) FOREIGN KEY REFERENCES KASIR (KD_KASIR),
TANGGAL DATETIME NOT NULL,
KD_MEMBER CHAR (10) FOREIGN KEY REFERENCES MEMBER (KD_MEMBER),
TOTAL VARCHAR (10) NOT NULL 
);

CREATE TABLE KASIR(
KD_KASIR CHAR (10) PRIMARY KEY,
NAMA VARCHAR (50) NOT NULL,
USER_KASIR VARCHAR(50) NOT NULL,
PASS_KASIR VARCHAR (20) NOT NULL
);

CREATE TABLE DETAIL_PENJUALAN(
ID_DETAILPENJ CHAR (10) PRIMARY KEY,
HARGA NUMERIC (18,0) NOT NULL,
JUMLAH INT NOT NULL,
KD_BARANG CHAR (10) FOREIGN KEY REFERENCES BARANG (KD_BARANG),
NO_PAJAK CHAR (10) FOREIGN KEY REFERENCES PAJAK (NO_PAJAK),
NO_NOTA CHAR (5) FOREIGN KEY REFERENCES PENJUALAN (NO_NOTA),
KODE_OPERATOR VARCHAR (5) FOREIGN KEY REFERENCES OPERATOR (KODE_OPERATOR)
);


CREATE TABLE KREDIT(
NO_KREDIT CHAR (5) PRIMARY KEY,
NO_NOTA CHAR (5) FOREIGN KEY REFERENCES PENJUALAN (NO_NOTA),
TANGGAL_KREDIT DATETIME,
TGL_LUNAS DATETIME,
JUMLAH_BARANG INT NOT NULL,
LAMA_KREDIT VARCHAR (10) NOT NULL,
);


CREATE TABLE PAJAK(
NO_PAJAK CHAR (10) PRIMARY KEY,
JUMLAH_PAJAK INT NOT NULL,
TGL_BAYAR DATETIME
);


CREATE TABLE BARANG(
KD_BARANG CHAR (10) PRIMARY KEY,
NAMA_BARANG VARCHAR (30) NOT NULL,
HARGA_BARANG NUMERIC (18,0) NOT NULL,
JUMLAH_BARANG INT NOT NULL,
STOK VARCHAR (10)
);


CREATE TABLE PEMBELIAN(
KD_BELI CHAR (10) PRIMARY KEY,
TGL_BELI DATETIME,
JUMLAH_BARANG INT NOT NULL,
SUBTOTAL VARCHAR (10) NOT NULL
);

CREATE TABLE DETAIL_PEMBELIAN(
KD_BELI CHAR (10) FOREIGN KEY REFERENCES PEMBELIAN (KD_BELI),
KD_BARANG CHAR (10) FOREIGN KEY REFERENCES BARANG (KD_BARANG),
TGL_BELI DATETIME,
TOTAL VARCHAR (10) NOT NULL
);

CREATE TABLE SUPPLIER(
KD_SUPPLIER CHAR (10) PRIMARY KEY,
KD_BELI CHAR (10) FOREIGN KEY REFERENCES PEMBELIAN (KD_BELI),
NAMA VARCHAR(50) NOT NULL,
ALAMAT VARCHAR (100) NOT NULL,
NO_TELP VARCHAR (12) NOT NULL, 
EMAIL VARCHAR (20) NOT NULL
);

SELECT * FROM RETUR
SELECT * FROM CUSTOMERSERVICE
SELECT * FROM MERCHANDISE
SELECT * FROM MEMBER
SELECT * FROM PENJUALAN
SELECT * FROM KASIR
SELECT * FROM DETAIL_PENJUALAN
SELECT * FROM KREDIT
SELECT * FROM PAJAK
SELECT * FROM BARANG
SELECT * FROM PEMBELIAN
SELECT * FROM DETAIL_PEMBELIAN
SELECT * FROM SUPPLIER

DROP TABLE PENJUALAN

CREATE TABLE OPERATOR(
KODE_OPERATOR VARCHAR(5) PRIMARY KEY,
NAMA_OPERATOR VARCHAR (50) NOT NULL,
USERID VARCHAR (20) NOT NULL,
PASS VARCHAR (20) NOT NULL,
LEVEL_OPERATOR VARCHAR (30) NOT NULL
);
 
SELECT * FROM OPERATOR
INSERT INTO OPERATOR VALUES ('OP-01','anida','anidanip','anida12','customerservice')
INSERT INTO OPERATOR VALUES ('OP-02','putri','putria','putria26','kasir')
INSERT INTO OPERATOR VALUES ('OP-03','intan','intania','intan123','pemilik')

INSERT INTO KREDIT VALUES ('K0001', 'N0001', '2019/01/12', '2019/02/19', 1, 'SEMINGGU')

INSERT INTO PENJUALAN (NO_NOTA, KD_KASIR, TANGGAL, KD_MEMBER, TOTAL)
VALUES ('N0001', 'KS001', '2019/01/12', 'KM001', 20000)

INSERT INTO MEMBER VALUES ('KM001', 'ANIDA', 'JANTI', '089234234123', '0231123234524', 'anida12@gmail.com', '100')

INSERT INTO KASIR VALUES ('KS001', 'WAHID', 'wahid', 'wahid12')